[package]
name = "new-base"
version = "0.4.1"
description = "Deprecated"
repository = "https://github.com/rvanasa/new-motoko-base"
keywords = []
license = "Apache-2.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
fuzz = "0.2.1"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.1@5ba5f52bd9a5649dedf5e2a1ccd55d98ed7ff982"

[toolchain]
moc = "0.14.5"
wasmtime = "21.0.0"
