[package]
name = "new-base"
version = "0.0.0"
description = "The new Motoko base library (preview)"
repository = "https://github.com/dfinity/new-motoko-base"
keywords = [ "base" ]
license = "Apache-2.0"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"
test = "2.1.0"

[toolchain]
moc = "0.14.1"
wasmtime = "17.0.0"
