[package]
name = "new-base"
version = "0.4.0"
description = "The new Motoko base library (preview)"
repository = "https://github.com/dfinity/new-motoko-base"
keywords = [ "base" ]
license = "Apache-2.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
fuzz = "0.2.1"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.1@5ba5f52bd9a5649dedf5e2a1ccd55d98ed7ff982"
base-0-14-8 = "https://github.com/dfinity/motoko-base#9e6010595cb9bad5b637ab7438fd11dc79a21a06"

[toolchain]
moc = "0.14.8"
wasmtime = "21.0.0"
