[package]
name = "core"
version = "1.0.0"
description = "The Motoko standard library"
repository = "https://github.com/dfinity/motoko-core"
keywords = [
  "core",
  "base",
  "data-structure",
  "stable-memory",
  "persistent",
]
license = "Apache-2.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
fuzz = "1.0.0"
matchers = "2.1.0"
base-0-14-13 = "https://github.com/dfinity/motoko-base#moc-0.14.13@794174a307975c225cfb26b57f73e38a841c0415"

[requirements]
moc = "0.16.3-implicits-19"

[toolchain]
moc = "0.16.3-implicits-19"
wasmtime = "35.0.0"
