[package]
name = "new-base"
version = "0.3.0"
description = "The new Motoko base library (preview)"
repository = "https://github.com/dfinity/new-motoko-base"
keywords = [ "base" ]
license = "Apache-2.0"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.1@5ba5f52bd9a5649dedf5e2a1ccd55d98ed7ff982"
test = "2.1.0"

[toolchain]
moc = "0.13.7"
wasmtime = "17.0.0"
