name: Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-24.04
    name: Run Benchmarks and Comment on PR or Upload on push

    steps:
      - uses: actions/checkout@v4

      # Installation steps TODO: split this workflow into Benchmark Comment and Benchmark Upload to get rid of 'if' statements, move the steps below to a separate workflow and reuse in both
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Confirm successful installation
        run: dfx --version
      - name: Install dfx cache
        run: dfx cache install
      - name: Cache mops packages
        uses: actions/cache@v4
        with:
          key: mops-packages-${{ hashFiles('mops.toml') }}
          restore-keys: |
            mops-packages-${{ hashFiles('mops.toml') }}
            mops-packages-
          path: |
            ~/.cache/mops
      - name: Install mops & mocv
        run: |
          npm --yes -g i ic-mops
          mops install
          mops toolchain init
          # mops toolchain use moc latest # TODO: we should use the compatible one

          # set moc path for dfx to use
          echo "DFX_MOC_PATH=$(mops toolchain bin moc)" >> $GITHUB_ENV

      - name: Checkout out the branch with benchmark results
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: benchmark-results
          path: .benchmark-results-branch/
      - name: Move Saved Benchmarks
        if: github.event_name == 'pull_request'
        run: mv .benchmark-results-branch/.bench .bench
      - name: Benchmarks Table
        if: github.event_name == 'pull_request'
        id: benchmarks
        run: |  # Make sure to use the same flags as in the `mops bench` command below!
          mops bench --compare 2>&1 | tee benchmark_results.txt
          echo "result<<EOF" >> $GITHUB_OUTPUT
          cat benchmark_results.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Benchmark Results
      - name: Create or update comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.benchmarks.outputs.result }}
            **Note**: Renamed benchmarks cannot be compared. Refer to the [current baseline](https://github.com/dfinity/new-motoko-base/tree/benchmark-results) for manual comparison.
          edit-mode: replace
      
      - name: Generate Benchmark Results
        if: github.event_name != 'pull_request'
        run: | # Make sure to use the same flags as in the `mops bench` command above!
          mops bench --save 2>&1 | tee bench-results.md 
      - name: Move Generated Results
        if: github.event_name != 'pull_request'
        run: |
          mkdir .bench-br
          mv .bench .bench-br/.bench
          mv bench-results.md .bench-br/README.md
      - name: Upload benchmark results
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: benchmark-results
          folder: .bench-br
