name: Check Motoko Changes

on:
  workflow_call:
    outputs:
      has_mo_changes:
        description: "Whether there are any Motoko file changes"
        value: ${{ jobs.check.outputs.has_mo_changes }}

jobs:
  check:
    runs-on: ubuntu-24.04
    outputs:
      has_mo_changes: ${{ steps.check_mo_changes.outputs.has_mo_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for Motoko file changes
        id: check_mo_changes
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha || '$(git rev-parse HEAD~1)' }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          if ! git diff --name-only $BASE_SHA $HEAD_SHA | grep -q '\.mo$'; then
            echo "has_mo_changes=false" >> $GITHUB_OUTPUT
            echo "No Motoko file changes detected"
          else
            echo "has_mo_changes=true" >> $GITHUB_OUTPUT
          fi 