name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    concurrency: gh-pages-${{ github.ref }}
    runs-on: ubuntu-20.04
    env:
      PR_PATH: pull/${{github.event.number}}
    steps:
      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        if: github.ref != 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "⏳ Deploying docs preview..."

      - name: Set domain
        run: echo "DOMAIN=dfinity.github.io" >> $GITHUB_ENV

      - name: Checkout website repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup dfx
        uses: dfinity/setup-dfx@main

      - run: dfx cache install

      - name: Set production base URL
        run: echo "BASE_URL=https://${{ env.DOMAIN }}/${{ github.event.repository.name }}/" >> $GITHUB_ENV

      - name: Build docs if main branch
        if: github.ref == 'refs/heads/main'
        run: npm run docs

      - name: Deploy if main branch
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./docs

      - name: Set base URL for preview if PR
        if: github.ref != 'refs/heads/main'
        run: echo "BASE_URL=https://${{ env.DOMAIN }}/${{ github.event.repository.name }}/${{ env.PR_PATH}}/" >> $GITHUB_ENV

      - name: Build PR preview website
        if: github.ref != 'refs/heads/main'
        run: npm run docs

      - name: Deploy to PR preview
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref != 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./docs
          target-folder: ${{ env.PR_PATH }}

      - name: Update comment
        uses: hasura/comment-progress@v2.2.0
        if: github.ref != 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "✨ Preview (${{ github.event.after }}):\n\n> **${{ env.BASE_URL }}**\n\n[Source code](https://github.com/${{ github.repository }}/tree/gh-pages/${{ env.PR_PATH }}/)"
