name: Mops Cache

on:
  workflow_call:

jobs:
  cache-mops:
    runs-on: ubuntu-24.04
    steps:
      - name: Cache mops packages
        uses: actions/cache@v4
        with:
          key: mops-packages-${{ hashFiles('mops.toml') }}
          restore-keys: |
            mops-packages-${{ hashFiles('mops.toml') }}
            mops-packages-
          path: |
            ~/.cache/mops 