name: Setup Environment

on: 
  workflow_call:
    inputs:
      dfx:
        description: 'Install dfx'
        required: false
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Cache mops packages
        uses: actions/cache@v4
        with:
          key: mops-packages-${{ hashFiles('mops.toml') }}
          restore-keys: |
            mops-packages-${{ hashFiles('mops.toml') }}
            mops-packages-
          path: |
            ~/.cache/mops
      - run: npm ci
      - run: npx mops toolchain init
      - name: Install dfx
        if: ${{ inputs.dfx }}
        uses: dfinity/setup-dfx@main
      - name: Install dfx cache
        if: ${{ inputs.dfx }}
        run: dfx cache install
