name: Sync main and next-moc
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge main -> next-moc
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: next-moc
          github_token: ${{ github.token }}
