name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-changelog:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      - uses: ./.github/actions/setup
        with:
          setup-mops: false
      - run: npm run validate:changelog
      - name: Check for Motoko file changes
        run: |
          HEAD_SHA="${{ github.sha }}"
          BASE_SHA="${{ github.event.pull_request.base.sha || '$(git rev-parse HEAD~1)' }}"
          echo "HEAD_SHA: $HEAD_SHA"
          echo "BASE_SHA: $BASE_SHA"

          if git diff --name-only $BASE_SHA $HEAD_SHA | grep -q '^src/.*\.mo$'; then
            echo "Found modified Motoko files, checking for Changelog.md update..."
            if git diff --name-only $BASE_SHA $HEAD_SHA | grep -q '^Changelog\.md$'; then
              echo "Changelog.md was updated"
            else
              echo "Error: Motoko files were modified but Changelog.md was not updated"
              exit 1
            fi
          fi

  validate-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          setup-mops: false
      - run: npm run validate:version

  validate-api:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm run validate:api
      - name: Check for API changes
        run: |
          DIFF=$(git diff -- validation/api)
          if [ -n "$DIFF" ]; then
            echo "API changes:"
            echo "$DIFF"
            echo
            echo '>>> If this looks correct, please run the command `npm run validate` and commit the output.'
            echo
            exit 1
          fi

  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm run format:check

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check for Motoko file changes in 'src' directory
        id: check_mo_changes
        run: |
          if ! git diff --name-only ${{ github.event.pull_request.base.sha || 'HEAD^' }} HEAD | grep -q '\.mo$'; then
            echo "No Motoko file changes in src directory detected, skipping tests"
            exit 0
          fi
      - run: npm test
