name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-motoko-changes:
    uses: ./.github/workflows/check-motoko-changes.yml

  validate-changelog:
    needs: check-motoko-changes
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          setup-mops: false
      - run: npm run validate:changelog
      - name: Validate Changelog for Motoko changes
        if: needs.check-motoko-changes.outputs.has_src_mo_changes == 'true'
        run: |
          if [ "${{ needs.check-motoko-changes.outputs.has_changelog_changes }}" != "true" ]; then
            echo "Error: Motoko files were modified but Changelog.md was not updated"
            exit 1
          fi
          echo "Changelog.md was updated"

  validate-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          setup-mops: false
      - run: npm run validate:version

  validate-api:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm run validate:api
      - name: Check for API changes
        run: |
          DIFF=$(git diff -- validation/api)
          if [ -n "$DIFF" ]; then
            echo "API changes:"
            echo "$DIFF"
            echo
            echo '>>> If this looks correct, please run the command `npm run validate` and commit the output.'
            echo
            exit 1
          fi

  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm run format:check

  test:
    needs: check-motoko-changes
    if: needs.check-motoko-changes.outputs.has_mo_changes == 'true'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm test
